[{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 1,
	"startColumn": 2,
	"endLineNumber": 1,
	"endColumn": 4
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 1,
	"startColumn": 6,
	"endLineNumber": 1,
	"endColumn": 7
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 3,
	"startColumn": 130,
	"endLineNumber": 3,
	"endColumn": 131
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 3,
	"startColumn": 132,
	"endLineNumber": 3,
	"endColumn": 134
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 89,
	"endLineNumber": 4,
	"endColumn": 90
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 90,
	"endLineNumber": 4,
	"endColumn": 91
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 92,
	"endLineNumber": 4,
	"endColumn": 94
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 95,
	"endLineNumber": 4,
	"endColumn": 97
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 320,
	"endLineNumber": 4,
	"endColumn": 321
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 324,
	"endLineNumber": 4,
	"endColumn": 326
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 5,
	"startColumn": 103,
	"endLineNumber": 5,
	"endColumn": 104
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 5,
	"startColumn": 106,
	"endLineNumber": 5,
	"endColumn": 108
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 6,
	"startColumn": 139,
	"endLineNumber": 6,
	"endColumn": 140
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 6,
	"startColumn": 142,
	"endLineNumber": 6,
	"endColumn": 143
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 6,
	"startColumn": 152,
	"endLineNumber": 6,
	"endColumn": 153
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 6,
	"startColumn": 156,
	"endLineNumber": 6,
	"endColumn": 157
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 7,
	"startColumn": 96,
	"endLineNumber": 7,
	"endColumn": 97
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 7,
	"startColumn": 99,
	"endLineNumber": 7,
	"endColumn": 100
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "528",
	"severity": 8,
	"message": "Property keys must be doublequoted",
	"source": "snippets",
	"startLineNumber": 7,
	"startColumn": 109,
	"endLineNumber": 7,
	"endColumn": 110
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "515",
	"severity": 8,
	"message": "Colon expected",
	"source": "snippets",
	"startLineNumber": 7,
	"startColumn": 113,
	"endLineNumber": 7,
	"endColumn": 114
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"severity": 8,
	"message": "End of file expected.",
	"source": "snippets",
	"startLineNumber": 7,
	"startColumn": 460,
	"endLineNumber": 7,
	"endColumn": 463
},{
	"resource": "/JMARRUJO91/jazmyne/.vscode/walmart.code-snippets",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "520",
	"severity": 4,
	"message": "Duplicate object key",
	"source": "snippets",
	"startLineNumber": 4,
	"startColumn": 320,
	"endLineNumber": 4,
	"endColumn": 321
}]
